services:
  mariadb:
    image: mariadb:10.5.5
    restart: always
    environment:
      MYSQL_USER: sqlpad_user
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: sqlpad
      MYSQL_ROOT_PASSWORD: admin

  sqlpad:
    image: sqlpad/sqlpad:5.6.0
    hostname: 'sqlpad'
    depends_on:
      - 'mariadb'
    ports:
      - '3000:3000'
    environment:
      SQLPAD_ADMIN: 'admin@sqlpad.com'
      SQLPAD_ADMIN_PASSWORD: 'admin'
      SQLPAD_APP_LOG_LEVEL: debug
      SQLPAD_WEB_LOG_LEVEL: warn
      SQLPAD_SEED_DATA_PATH: /etc/sqlpad/seed-data
      SQLPAD_BACKEND_DB_URI: mariadb://sqlpad_user:admin@mariadb:3306/sqlpad
      SQLPAD_SESSION_STORE: 'database'
      SQLPAD_DB_PATH: mariadb://sqlpad_user:admin@mariadb:3306/sqlpad  # <-- fixed here
      SQLPAD_DB_IN_MEMORY: 'false'
      SQLPAD_QUERY_RESULT_STORE: 'database'
      SQLPAD_CONNECTIONS__mariad__name: 'MariaDB Demo'
      SQLPAD_CONNECTIONS__mariad__driver: mysql
      SQLPAD_CONNECTIONS__mariad__host: mariadb
      SQLPAD_CONNECTIONS__mariad__port: 3306
      SQLPAD_CONNECTIONS__mariad__database: sqlpad
      SQLPAD_CONNECTIONS__mariad__username: sqlpad_user
      SQLPAD_CONNECTIONS__mariad__password: admin
    volumes:
      - ./seed-data:/etc/sqlpad/seed-data
